<a href="https://colab.research.google.com/github/yhk775206/LA2/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


##### 라이브러리(패키지) 로드

In [ ]:
import numpy as np

#### 2. 벡터, 행렬 연산, 그래프 그리기
##### 프린트

In [ ]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값: \n", x)
  print(" ")

In [ ]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값: 
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값: 
 [5 2 3]
 


In [ ]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값: 
 [[1 2 3]
 [4 5 6]]
 


In [ ]:
a = np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값: 
 [[0. 0.]
 [0. 0.]]
 


In [ ]:
a = np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [ ]:
a = np.eye(3,3)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [ ]:
a = np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: 
 [[0.71854187 0.64611134 0.097503   0.80433283]
 [0.1930785  0.09574521 0.58847221 0.25559805]
 [0.39232344 0.30151385 0.26551274 0.76858993]
 [0.83124846 0.55188686 0.69096674 0.75057974]]
 


In [ ]:
a = np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값: 
 [[ 0.11284161 -0.01068591  0.09542687  0.87404957]
 [ 0.85632645 -0.25939638  0.21517415 -1.12653077]
 [ 1.21777463 -1.18993305 -0.48635165  1.50824853]
 [ 0.98481721  2.02234345 -0.10992008 -2.07057658]]
 
